name: Hardhat Build
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Setup NodeJS 20.18.1
              uses: actions/setup-node@v2
              with:
                node-version: 20.18.1
                cache: npm
            - name: Show NodeJS version 
              run: npm --version
            
            - name: Install Hardhat
              run: npm install --save-dev hardhat@2.22.18
            
            - name: Install Hardhat Dependencies
              run: npm ci

            - name: Install Solhint
              run: npm install -g solhint
            
            - name: Show Solhint version 
              run: solhint --version
            
            - name: Run Lint
              run: solhint 'contracts/**/*.sol'
            
            - name: Run Hardhat Test
              run: npx hardhat test